### ISSUE TITLE
About CNN-Base

### ISSUE THREAD

**Issue by myt889** [XsLangley/TDGAN#3]
Hi，I still have a question about the CNN-Base in experiments of your paper. It means VGG or ResNet,or any other CNNs ? Could you give the details? Thanks a lot for your kindness.

**Comment by XsLangley** [comment]
> Hi，I still have a question about the CNN-Base in experiments of your paper. It means VGG or ResNet,or any other CNNs ? Could you give the details? Thanks a lot for your kindness.

Hi, the CNN-Base is the expression discriminator of TDGAN. Since the expression discriminator is also trained by doing multi-class expression classification, we can take it as a baseline classifier for comparison. Also, the architecture of the expression discriminator is totally the same as the encoder of the generator of TDGAN. By comparing the recognition performance between the TDGAN and the CNN-base, we can find how much improvement can be attained by implementing such a disentangling framework. The detailed network architecture configuration can be found in Table I. 
I don't use VGG or ResNet for comparison but you can have a try. I remember that ResNet can get a 99% accuracy on RaFD (the result is reported in the paper or supplementary materials of StarGAN I guess, but their details on the experimental setting may be different). Also, when I design TDGAN, I leave some room for modification by separating the encoder part and the Expression Classification Module (M_ER, the green part in Fig.2 of TDGAN paper). If you are interested, you can easily replace the encoder part of the generator of TDGAN with ResNet or VGG, or other more complex frameworks. However, a very deep model is suitable for classification task but I guess it may not be suitable for image generation because details can get lost as it goes deeper (unless you introduce some other techniques like skip-connection to recover some low-level details). But anyway, we can only know the actual result after we try it :)

**Comment by myt889** [comment]
Thanks again for your good proposal.

**Comment by myt889** [comment]
Thanks again for your good proposal.
